# 实习6 空间网络构建和查询

姓名：秦卫付

学号：3170106249

**实习目的：**熟悉空间网络的基本概念和常见的空间网络分析和查询；掌握SQL3中的WITH RECURSIVE语句，熟悉从几何对象模型到空间网络模型的转换，掌握基于pgRouting的空间网络模型构建，熟悉pgRouting的最短路径算法，并会灵活运用解决一些空间网络的连通性查询问题。

**注意事项：**
* SQL语句的错误输出为乱码时，修改SET client_encoding = 'GBK';或SET client_encoding = 'UTF-8';，重新连接数据库
* Jupyter Notebook对SQL语句的错误提示较弱，可以先在pgAdmin 4上执行，查看详细的错误信息
* 实习6总分50分，实习考察的题目后面标了具体分数，可以相互讨论思路，作业抄袭或雷同都要扣分
* 实习6\_学号\_姓名.ipynb替换其中的学号和姓名，包含执行结果，和jsonData目录一起压缩为__实习6\_学号\_姓名.rar__，发送到zjusdb@163.com
* 实习6截止日期**2019.6.2**

### 0. With Recursive和pgRouting 2.6帮助文档

With Recursive是SQL3新增加的计算传递闭包语句，PostgreSQL实现了<a href = 'http://www.postgresql.org/docs/current/static/queries-with.html' target=\"_blank\">With Recursive</a>语句，请阅读并理解PostgreSQL帮助文档7.8.1 SELECT in WITH的Recursive Query Evaluation步骤。**With Recursive语句需要避免死循环，如果运行时间过长，可以先在pgAdmin III/4测试运行时间，或使用limit限制结果数目。**

pgRouting扩展了PostgreSQL/PostGIS地理空间数据库，提供了地理导航和网络分析功能。从几何对象模型构建空间网络模型，需要使用pgr_createTopology，pgr_analyzeGraph，pgr_nodeNetwork，地理导航可以使用pgr_dijkstra等最短路径算法。实习使用pgRouting 2.2/2.4，请在使用相关函数前，仔细阅读<a href = 'http://docs.pgrouting.org/latest/en/index.html' target=\"_blank\">pgRouting</a>的函数帮助文档。

### 1. 观看访谈视频和阅读相关材料，回答问题（3分）

观看From GPS and Google Maps to Spatial Computing课程的[Module 3](http://www.cad.zju.edu.cn/home/ybtao/sdb/resources/Module%203.rar) Spatial Networks</a>的3-10 Dr. Dev Oliver at ESRI和3-11 Dr. Betsy George at Oracle Spatial的访谈视频（或阅读字幕），回答以下问题。

1.1  Dr. Betsy George提到飓风来临时，撤退方案不能直接使用最短路径算法，原因是什么？（1分）

the roads have capacities and you cannot push everybody to move,along the same shortest path possible from the source to the destination.

1.2 Dr. Dev Oliver和Dr. Betsy George都谈到了企业使用的空间网络和课本上的空间网络的差异，至少给出2条差异描述。（2分）

1、the text book model actually treats the graph as static，但是企业使用的空间网络是动态的；
2、课本上两节点之间的cost是固定，企业中的是随时间变化的；
3、课本上要素的特征较单一，而企业使用的空间网络是丰富多彩的，其包含的特征较多。

### 2. 美国航空网络构建与查询（14分）

通过pgAdmin 4在PostgreSQL数据库中创建lab6数据库，增加postgis和pgRouting扩展(create extension postgis, create extension pgrouting)，并连接该数据库。
<img src = "usairports.png" width = 800>

In [1]:
%load_ext sql
from geom_display import display

# display([result1,restult2...], divId, zoom)对数组中所有的result数据进行几何展示，
# result的关系类型至少包含(gid，geom，name)，zoom为放缩比例, name是在地图上描述geom的名词

In [2]:
%%sql postgresql://postgres:qwf123@localhost:5432/lab6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF-8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

Done.
Done.
Done.
Done.
Done.
Done.

[]

仔细阅读以下SQL语句，创建美国机场、机场关系和机场航班关系，理解航空网络的构建，并导入相应数据，完成以下查询。

In [3]:
%%sql

Drop Table if exists AIRPORT_LIST;
Drop Table if exists AIRPORT_NODE;
Drop Table if exists AIRPORT_LINK;

create table AIRPORT_LIST
(
    AIRPORT_ID INT,
    AIRPORT_NAME VARCHAR(50)
);

create table AIRPORT_NODE
(
     NODE_ID   INT PRIMARY KEY,
     NODE_NAME VARCHAR(200),
     NODE_TYPE VARCHAR(200),
     ACTIVE    VARCHAR(1),
     PARTITION_ID INT,
     GEOMETRY geometry(POINT, 4326)
);

create table AIRPORT_LINK
(
    LINK_ID     INT PRIMARY KEY,
    LINK_NAME   VARCHAR(200),
    START_NODE_ID   INT NOT NULL,
    END_NODE_ID     INT NOT NULL,
    LINK_TYPE       VARCHAR(200),
    ACTIVE      VARCHAR(1),
    LINK_LEVEL  INT,
    GEOMETRY    geometry(MultiLineString, 4326),
    COST            INT,
    BIDIRECTED      VARCHAR(1)                                    
);

copy airport_list from  'D://desktop//geodatabase//lab//lab6//data//airport_list.txt' delimiter '#';
copy airport_node from  'D://desktop//geodatabase//lab//lab6//data//airport_node.txt' delimiter '#';
copy airport_link from  'D://desktop//geodatabase//lab//lab6//data//airport_link.txt' delimiter '#';

 * postgresql://postgres:***@localhost:5432/lab6
Done.
Done.
Done.
Done.
Done.
Done.
293 rows affected.
293 rows affected.
4093 rows affected.

[]

2.1 (练习题) 查询美国机场之间的单向航班数目，即存在从A到B的航班，但不存在从B到A的航班。

In [4]:
%%sql select count(*) as count
from airport_link as a
where not exists
(
    select 
    from airport_link as b
    where b.start_node_id=a.end_node_id
    and b.end_node_id=a.start_node_id
);

 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.

[(25L,)]

2.2 查询“Durango, CO”机场最多一次转机能够达到的机场名称和AIRPORT_ID，使用With Recursive实现。（2分）

非With Recursive实现

In [8]:
%%sql 
select end_node_id, (select airport_name from airport_list where airport_id = end_node_id)
from airport_list, airport_link
where airport_name = 'Durango, CO' and airport_id = start_node_id
union
select L2.end_node_id, (select airport_name from airport_list where airport_id = L2.end_node_id)
from airport_list, airport_link L1, airport_link L2
where airport_name = 'Durango, CO' and airport_id = L1.start_node_id and L1.end_node_id = L2.start_node_id

 * postgresql://postgres:***@localhost:5432/lab6
186 rows affected.

[(10721, u'Boston, MA'),
 (11986, u'Grand Rapids, MI'),
 (14457, u'Rapid City, SD'),
 (10713, u'Boise, ID'),
 (10821, u'Baltimore, MD'),
 (14307, u'Providence, RI'),
 (15376, u'Tucson, AZ'),
 (11540, u'El Paso, TX'),
 (12951, u'Lafayette, LA'),
 (10693, u'Nashville, TN'),
 (11637, u'Fargo, ND'),
 (11140, u'Corpus Christi, TX'),
 (11278, u'Washington, DC'),
 (13930, u'Chicago, IL'),
 (14489, u'Bend/Redmond, OR'),
 (12953, u'New York, NY'),
 (13367, u'Moline, IL'),
 (13377, u'Monroe, LA'),
 (11413, u'Durango, CO'),
 (11697, u'Fort Lauderdale, FL'),
 (12156, u'Helena, MT'),
 (13230, u'Harrisburg, PA'),
 (10620, u'Billings, MT'),
 (12003, u'Great Falls, MT'),
 (15401, u'Texarkana, AR'),
 (12012, u'Gunnison, CO'),
 (10792, u'Buffalo, NY'),
 (14543, u'Rock Springs, WY'),
 (15304, u'Tampa, FL'),
 (14635, u'Fort Myers, FL'),
 (10155, u'Waco, TX'),
 (14771, u'San Francisco, CA'),
 (14679, u'San Diego, CA'),
 (11122, u'Casper, WY'),
 (12191, u'Houston, TX'),
 (14252, u'Pasco/Kennewick/Richland, WA'),
 (14843, u'San Juan, PR'),
 (14107, u'Phoenix, AZ'),
 (11259, u'Dallas, TX'),
 (14952, u'Springfield, IL'),
 (13495, u'New Orleans, LA'),
 (11905, u'Longview, TX'),
 (10529, u'Hartford, CT'),
 (10279, u'Amarillo, TX'),
 (12945, u'Lexington, KY'),
 (11109, u'Colorado Springs, CO'),
 (14783, u'Springfield, MO'),
 (11503, u'Eagle, CO'),
 (11423, u'Des Moines, IA'),
 (11867, u'Garden City, KS'),
 (12478, u'New York, NY'),
 (13422, u'Mobile, AL'),
 (13290, u'Manhattan/Ft. Riley, KS'),
 (11150, u'Columbus, GA'),
 (10627, u'Bismarck/Mandan, ND'),
 (10980, u'Chattanooga, TN'),
 (10423, u'Austin, TX'),
 (11823, u'Fort Wayne, IN'),
 (14683, u'San Antonio, TX'),
 (11865, u'Gillette, WY'),
 (11097, u'Cody, WY'),
 (11067, u'Champaign/Urbana, IL'),
 (14730, u'Louisville, KY'),
 (13244, u'Memphis, TN'),
 (11066, u'Columbus, OH'),
 (12511, u'Joplin, MO'),
 (14814, u'Shreveport, LA'),
 (11921, u'Grand Junction, CO'),
 (10781, u'Baton Rouge, LA'),
 (11995, u'Greensboro/High Point, NC'),
 (14027, u'West Palm Beach/Palm Beach, FL'),
 (15249, u'Tallahassee, FL'),
 (13232, u'Chicago, IL'),
 (14747, u'Seattle, WA'),
 (11982, u'Killeen, TX'),
 (10140, u'Albuquerque, NM'),
 (10136, u'Abilene, TX'),
 (10994, u'Charleston, SC'),
 (14674, u'Santa Fe, NM'),
 (14831, u'San Jose, CA'),
 (12915, u'Lake Charles, LA'),
 (13158, u'Midland/Odessa, TX'),
 (13830, u'Kahului, HI'),
 (14908, u'Santa Ana, CA'),
 (11775, u'Sioux Falls, SD'),
 (14108, u'Peoria, IL'),
 (15016, u'St. Louis, MO'),
 (15919, u'Fayetteville, AR'),
 (14588, u'Roswell, NM'),
 (11973, u'Gulfport/Biloxi, MS'),
 (15370, u'Tulsa, OK'),
 (10868, u'Columbia, SC'),
 (11648, u'Kalispell, MT'),
 (13486, u'Missoula, MT'),
 (11996, u'Greer, SC'),
 (13931, u'Norfolk, VA'),
 (11298, u'Dallas/Fort Worth, TX'),
 (11884, u'Spokane, WA'),
 (14262, u'Palm Springs, CA'),
 (13303, u'Miami, FL'),
 (13796, u'Oakland, CA'),
 (15412, u'Knoxville, TN'),
 (13851, u'Oklahoma City, OK'),
 (14100, u'Philadelphia, PA'),
 (13296, u'Manchester, NH'),
 (11193, u'Cincinnati, OH'),
 (13029, u'Lincoln, NE'),
 (13433, u'Minot, ND'),
 (10561, u'Bakersfield, CA'),
 (13204, u'Orlando, FL'),
 (13342, u'Milwaukee, WI'),
 (12992, u'Little Rock, AR'),
 (14960, u'Wichita Falls, TX'),
 (10397, u'Atlanta, GA'),
 (10185, u'Alexandria, LA'),
 (12896, u'Lubbock, TX'),
 (13487, u'Minneapolis, MN'),
 (13476, u'Monterey, CA'),
 (12339, u'Indianapolis, IN'),
 (13198, u'Kansas City, MO'),
 (10599, u'Birmingham, AL'),
 (14524, u'Richmond, VA'),
 (12278, u'Wichita, KS'),
 (11612, u'Evansville, IN'),
 (11049, u'College Station/Bryan, TX'),
 (12266, u'Houston, TX'),
 (12954, u'Long Beach, CA'),
 (13502, u'Montrose/Delta, CO'),
 (12441, u'Jackson, WY'),
 (15624, u'Valparaiso, FL'),
 (12892, u'Los Angeles, CA'),
 (14685, u'Savannah, GA'),
 (14842, u'San Angelo, TX'),
 (11603, u'Eugene, OR'),
 (13256, u'Mission/McAllen/Edinburg, TX'),
 (10372, u'Aspen, CO'),
 (11057, u'Charlotte, NC'),
 (14570, u'Reno, NV'),
 (10666, u'Bellingham, WA'),
 (12448, u'Jackson/Vicksburg, MS'),
 (14893, u'Sacramento, CA'),
 (11778, u'Fort Smith, AR'),
 (15411, u'Tyler, TX'),
 (14869, u'Salt Lake City, UT'),
 (14057, u'Portland, OR'),
 (11618, u'Newark, NJ'),
 (14098, u'Newport News/Williamsburg, VA'),
 (12094, u'Hayden, CO'),
 (13891, u'Ontario, CA'),
 (12451, u'Jacksonville, FL'),
 (15380, u'Traverse City, MI'),
 (12982, u'Lihue, HI'),
 (13061, u'Laredo, TX'),
 (12280, u'Idaho Falls, ID'),
 (10685, u'Bloomington/Normal, IL'),
 (11695, u'Flagstaff, AZ'),
 (13871, u'Omaha, NE'),
 (12758, u'Kona, HI'),
 (14492, u'Raleigh/Durham, NC'),
 (10643, u'Branson, MO'),
 (11003, u'Cedar Rapids/Iowa City, IA'),
 (13264, u'Medford, OR'),
 (14122, u'Pittsburgh, PA'),
 (13485, u'Madison, WI'),
 (12264, u'Washington, DC'),
 (12891, u'Lawton/Fort Sill, OK'),
 (11042, u'Cleveland, OH'),
 (13277, u'Montgomery, AL'),
 (14698, u'San Luis Obispo, CA'),
 (11267, u'Dayton, OH'),
 (11292, u'Denver, CO'),
 (10747, u'Brownsville, TX'),
 (11638, u'Fresno, CA'),
 (12217, u'Huntsville, AL'),
 (10849, u'Bozeman, MT'),
 (11980, u'Grand Island, NE'),
 (10299, u'Anchorage, AK'),
 (11433, u'Detroit, MI'),
 (12173, u'Honolulu, HI'),
 (16218, u'Yuma, AZ'),
 (10874, u'Akron, OH'),
 (12889, u'Las Vegas, NV'),
 (14689, u'Santa Barbara, CA'),
 (14193, u'Pensacola, FL'),
 (10800, u'Burbank, CA'),
 (11630, u'Fairbanks, AK')]

With Recursive实现，对比两种实现方式实现的优缺点

In [7]:
%%sql 
with recursive X(end_node_id,depth)
as (select end_node_id , 
	0 from airport_link
	where start_node_id=(select airport_id from airport_list
					   where airport_name='Durango, CO')
    union
   select airport_link.end_node_id,depth+1 
   from airport_link,X
   where airport_link.start_node_id=X.end_node_id and depth<1)
   select distinct end_node_id,airport_name from X,airport_list
   where airport_id=end_node_id

 * postgresql://postgres:***@localhost:5432/lab6
186 rows affected.

[(12951, u'Lafayette, LA'),
 (10693, u'Nashville, TN'),
 (11413, u'Durango, CO'),
 (10620, u'Billings, MT'),
 (14771, u'San Francisco, CA'),
 (11905, u'Longview, TX'),
 (10529, u'Hartford, CT'),
 (11423, u'Des Moines, IA'),
 (12478, u'New York, NY'),
 (13422, u'Mobile, AL'),
 (11150, u'Columbus, GA'),
 (10627, u'Bismarck/Mandan, ND'),
 (11865, u'Gillette, WY'),
 (10994, u'Charleston, SC'),
 (13158, u'Midland/Odessa, TX'),
 (14108, u'Peoria, IL'),
 (14262, u'Palm Springs, CA'),
 (13303, u'Miami, FL'),
 (11612, u'Evansville, IN'),
 (12266, u'Houston, TX'),
 (13502, u'Montrose/Delta, CO'),
 (14842, u'San Angelo, TX'),
 (14570, u'Reno, NV'),
 (12448, u'Jackson/Vicksburg, MS'),
 (12982, u'Lihue, HI'),
 (11695, u'Flagstaff, AZ'),
 (11003, u'Cedar Rapids/Iowa City, IA'),
 (12264, u'Washington, DC'),
 (10747, u'Brownsville, TX'),
 (10874, u'Akron, OH'),
 (13377, u'Monroe, LA'),
 (14543, u'Rock Springs, WY'),
 (14252, u'Pasco/Kennewick/Richland, WA'),
 (14843, u'San Juan, PR'),
 (13495, u'New Orleans, LA'),
 (11097, u'Cody, WY'),
 (15249, u'Tallahassee, FL'),
 (13830, u'Kahului, HI'),
 (11775, u'Sioux Falls, SD'),
 (14588, u'Roswell, NM'),
 (10397, u'Atlanta, GA'),
 (12896, u'Lubbock, TX'),
 (12278, u'Wichita, KS'),
 (11603, u'Eugene, OR'),
 (10685, u'Bloomington/Normal, IL'),
 (11433, u'Detroit, MI'),
 (12173, u'Honolulu, HI'),
 (10721, u'Boston, MA'),
 (10821, u'Baltimore, MD'),
 (15376, u'Tucson, AZ'),
 (11278, u'Washington, DC'),
 (15401, u'Texarkana, AR'),
 (14679, u'San Diego, CA'),
 (10980, u'Chattanooga, TN'),
 (10423, u'Austin, TX'),
 (14683, u'San Antonio, TX'),
 (11982, u'Killeen, TX'),
 (10140, u'Albuquerque, NM'),
 (15919, u'Fayetteville, AR'),
 (11996, u'Greer, SC'),
 (11298, u'Dallas/Fort Worth, TX'),
 (13029, u'Lincoln, NE'),
 (10561, u'Bakersfield, CA'),
 (13342, u'Milwaukee, WI'),
 (13198, u'Kansas City, MO'),
 (12954, u'Long Beach, CA'),
 (10372, u'Aspen, CO'),
 (10666, u'Bellingham, WA'),
 (14869, u'Salt Lake City, UT'),
 (12094, u'Hayden, CO'),
 (10643, u'Branson, MO'),
 (13264, u'Medford, OR'),
 (11638, u'Fresno, CA'),
 (10849, u'Bozeman, MT'),
 (11980, u'Grand Island, NE'),
 (12889, u'Las Vegas, NV'),
 (11630, u'Fairbanks, AK'),
 (11986, u'Grand Rapids, MI'),
 (13930, u'Chicago, IL'),
 (13230, u'Harrisburg, PA'),
 (12945, u'Lexington, KY'),
 (14783, u'Springfield, MO'),
 (13290, u'Manhattan/Ft. Riley, KS'),
 (11066, u'Columbus, OH'),
 (10781, u'Baton Rouge, LA'),
 (14027, u'West Palm Beach/Palm Beach, FL'),
 (12915, u'Lake Charles, LA'),
 (13931, u'Norfolk, VA'),
 (14524, u'Richmond, VA'),
 (14685, u'Savannah, GA'),
 (11778, u'Fort Smith, AR'),
 (14057, u'Portland, OR'),
 (13891, u'Ontario, CA'),
 (14122, u'Pittsburgh, PA'),
 (12217, u'Huntsville, AL'),
 (10299, u'Anchorage, AK'),
 (10713, u'Boise, ID'),
 (14307, u'Providence, RI'),
 (12953, u'New York, NY'),
 (10792, u'Buffalo, NY'),
 (12191, u'Houston, TX'),
 (14952, u'Springfield, IL'),
 (14814, u'Shreveport, LA'),
 (11995, u'Greensboro/High Point, NC'),
 (13232, u'Chicago, IL'),
 (14831, u'San Jose, CA'),
 (15016, u'St. Louis, MO'),
 (11648, u'Kalispell, MT'),
 (10185, u'Alexandria, LA'),
 (13487, u'Minneapolis, MN'),
 (11049, u'College Station/Bryan, TX'),
 (14098, u'Newport News/Williamsburg, VA'),
 (13871, u'Omaha, NE'),
 (13277, u'Montgomery, AL'),
 (11292, u'Denver, CO'),
 (10800, u'Burbank, CA'),
 (14457, u'Rapid City, SD'),
 (14489, u'Bend/Redmond, OR'),
 (12003, u'Great Falls, MT'),
 (12012, u'Gunnison, CO'),
 (14635, u'Fort Myers, FL'),
 (10155, u'Waco, TX'),
 (10279, u'Amarillo, TX'),
 (11109, u'Colorado Springs, CO'),
 (13244, u'Memphis, TN'),
 (12511, u'Joplin, MO'),
 (14674, u'Santa Fe, NM'),
 (11973, u'Gulfport/Biloxi, MS'),
 (15370, u'Tulsa, OK'),
 (13796, u'Oakland, CA'),
 (13296, u'Manchester, NH'),
 (14960, u'Wichita Falls, TX'),
 (10599, u'Birmingham, AL'),
 (13256, u'Mission/McAllen/Edinburg, TX'),
 (14893, u'Sacramento, CA'),
 (12451, u'Jacksonville, FL'),
 (15380, u'Traverse City, MI'),
 (14492, u'Raleigh/Durham, NC'),
 (11042, u'Cleveland, OH'),
 (14698, u'San Luis Obispo, CA'),
 (11267, u'Dayton, OH'),
 (14193, u'Pensacola, FL'),
 (11540, u'El Paso, TX'),
 (11140, u'Corpus Christi, TX'),
 (11697, u'Fort Lauderdale, FL'),
 (12156, u'Helena, MT'),
 (14107, u'Phoenix, AZ'),
 (11867, u'Garden City, KS'),
 (14747, u'Seattle, WA'),
 (14908, u'Santa Ana, CA'),
 (11884, u'Spokane, WA'),
 (15412, u'Knoxville, TN'),
 (11193, u'Cincinnati, OH'),
 (13204, u'Orlando, FL'),
 (12992, u'Little Rock, AR'),
 (12339, u'Indianapolis, IN'),
 (12441, u'Jackson, WY'),
 (15624, u'Valparaiso, FL'),
 (12892, u'Los Angeles, CA'),
 (11057, u'Charlotte, NC'),
 (15411, u'Tyler, TX'),
 (11618, u'Newark, NJ'),
 (13061, u'Laredo, TX'),
 (12891, u'Lawton/Fort Sill, OK'),
 (16218, u'Yuma, AZ'),
 (11637, u'Fargo, ND'),
 (13367, u'Moline, IL'),
 (15304, u'Tampa, FL'),
 (11122, u'Casper, WY'),
 (11259, u'Dallas, TX'),
 (11503, u'Eagle, CO'),
 (11823, u'Fort Wayne, IN'),
 (11067, u'Champaign/Urbana, IL'),
 (14730, u'Louisville, KY'),
 (11921, u'Grand Junction, CO'),
 (10136, u'Abilene, TX'),
 (10868, u'Columbia, SC'),
 (13486, u'Missoula, MT'),
 (13851, u'Oklahoma City, OK'),
 (14100, u'Philadelphia, PA'),
 (13433, u'Minot, ND'),
 (13476, u'Monterey, CA'),
 (12280, u'Idaho Falls, ID'),
 (12758, u'Kona, HI'),
 (13485, u'Madison, WI'),
 (14689, u'Santa Barbara, CA')]

In [ ]:
with recursive 实现的话SQL语句易于理解，但是需要控制循环的次数
另一种实现的话SQL语句较难书写，优点不易出错

2.3 查询哪些机场最多一次转机能够达到"Bethel, AK"机场的机场名称和AIRPORT_ID，使用With Recursive实现。（2分）

In [9]:
%%sql
with recursive X(start_node_id,depth)
as (select start_node_id , 
	0 from airport_link
	where end_node_id=(select airport_id from airport_list
					   where airport_name='Bethel, AK')
    union
   select airport_link.start_node_id,depth+1 
   from airport_link,X
   where airport_link.end_node_id=X.start_node_id and depth<1)
   select distinct start_node_id,airport_name from X,airport_list
   where airport_id=start_node_id
   order by start_node_id

 * postgresql://postgres:***@localhost:5432/lab6
26 rows affected.

[(10165, u'Adak Island, AK'),
 (10170, u'Kodiak, AK'),
 (10245, u'King Salmon, AK'),
 (10299, u'Anchorage, AK'),
 (10551, u'Bethel, AK'),
 (10754, u'Barrow, AK'),
 (10926, u'Cordova, AK'),
 (11292, u'Denver, CO'),
 (11298, u'Dallas/Fort Worth, TX'),
 (11336, u'Dillingham, AK'),
 (11630, u'Fairbanks, AK'),
 (12173, u'Honolulu, HI'),
 (12266, u'Houston, TX'),
 (12523, u'Juneau, AK'),
 (12892, u'Los Angeles, CA'),
 (12954, u'Long Beach, CA'),
 (13487, u'Minneapolis, MN'),
 (13873, u'Nome, AK'),
 (13930, u'Chicago, IL'),
 (13970, u'Kotzebue, AK'),
 (14057, u'Portland, OR'),
 (14107, u'Phoenix, AZ'),
 (14709, u'Deadhorse, AK'),
 (14747, u'Seattle, WA'),
 (14771, u'San Francisco, CA'),
 (14869, u'Salt Lake City, UT')]

2.4 查询从"Dillingham, AK"机场到达 "Gainesville, FL"机场所需的最少转机次数，使用With Recursive实现。如果无法直接写出该语句，或运行时间过长，可以尝试枚举遍历法，即k从1，2，….不断增加，当k为多少，存在这样的路径。（3分）

In [11]:
%%sql with recursive X(end_node_id,depth)
as (select end_node_id , 
	0 from airport_link
	where start_node_id=(select airport_id from airport_list
					   where airport_name='Dillingham, AK')
    union
   select airport_link.end_node_id,depth+1 
   from airport_link,X
   where airport_link.start_node_id=X.end_node_id and x.end_node_id !=(select airport_id from airport_list
					                                              where airport_name='Gainesville, FL') and depth < 100)
   select distinct end_node_id,airport_name,depth from X,airport_list
   where airport_id=end_node_id and end_node_id =(select airport_id from airport_list
					                                              where airport_name='Gainesville, FL')
   order by depth

 * postgresql://postgres:***@localhost:5432/lab6
98 rows affected.

[(11953, u'Gainesville, FL', 3),
 (11953, u'Gainesville, FL', 4),
 (11953, u'Gainesville, FL', 5),
 (11953, u'Gainesville, FL', 6),
 (11953, u'Gainesville, FL', 7),
 (11953, u'Gainesville, FL', 8),
 (11953, u'Gainesville, FL', 9),
 (11953, u'Gainesville, FL', 10),
 (11953, u'Gainesville, FL', 11),
 (11953, u'Gainesville, FL', 12),
 (11953, u'Gainesville, FL', 13),
 (11953, u'Gainesville, FL', 14),
 (11953, u'Gainesville, FL', 15),
 (11953, u'Gainesville, FL', 16),
 (11953, u'Gainesville, FL', 17),
 (11953, u'Gainesville, FL', 18),
 (11953, u'Gainesville, FL', 19),
 (11953, u'Gainesville, FL', 20),
 (11953, u'Gainesville, FL', 21),
 (11953, u'Gainesville, FL', 22),
 (11953, u'Gainesville, FL', 23),
 (11953, u'Gainesville, FL', 24),
 (11953, u'Gainesville, FL', 25),
 (11953, u'Gainesville, FL', 26),
 (11953, u'Gainesville, FL', 27),
 (11953, u'Gainesville, FL', 28),
 (11953, u'Gainesville, FL', 29),
 (11953, u'Gainesville, FL', 30),
 (11953, u'Gainesville, FL', 31),
 (11953, u'Gainesville, FL', 32),
 (11953, u'Gainesville, FL', 33),
 (11953, u'Gainesville, FL', 34),
 (11953, u'Gainesville, FL', 35),
 (11953, u'Gainesville, FL', 36),
 (11953, u'Gainesville, FL', 37),
 (11953, u'Gainesville, FL', 38),
 (11953, u'Gainesville, FL', 39),
 (11953, u'Gainesville, FL', 40),
 (11953, u'Gainesville, FL', 41),
 (11953, u'Gainesville, FL', 42),
 (11953, u'Gainesville, FL', 43),
 (11953, u'Gainesville, FL', 44),
 (11953, u'Gainesville, FL', 45),
 (11953, u'Gainesville, FL', 46),
 (11953, u'Gainesville, FL', 47),
 (11953, u'Gainesville, FL', 48),
 (11953, u'Gainesville, FL', 49),
 (11953, u'Gainesville, FL', 50),
 (11953, u'Gainesville, FL', 51),
 (11953, u'Gainesville, FL', 52),
 (11953, u'Gainesville, FL', 53),
 (11953, u'Gainesville, FL', 54),
 (11953, u'Gainesville, FL', 55),
 (11953, u'Gainesville, FL', 56),
 (11953, u'Gainesville, FL', 57),
 (11953, u'Gainesville, FL', 58),
 (11953, u'Gainesville, FL', 59),
 (11953, u'Gainesville, FL', 60),
 (11953, u'Gainesville, FL', 61),
 (11953, u'Gainesville, FL', 62),
 (11953, u'Gainesville, FL', 63),
 (11953, u'Gainesville, FL', 64),
 (11953, u'Gainesville, FL', 65),
 (11953, u'Gainesville, FL', 66),
 (11953, u'Gainesville, FL', 67),
 (11953, u'Gainesville, FL', 68),
 (11953, u'Gainesville, FL', 69),
 (11953, u'Gainesville, FL', 70),
 (11953, u'Gainesville, FL', 71),
 (11953, u'Gainesville, FL', 72),
 (11953, u'Gainesville, FL', 73),
 (11953, u'Gainesville, FL', 74),
 (11953, u'Gainesville, FL', 75),
 (11953, u'Gainesville, FL', 76),
 (11953, u'Gainesville, FL', 77),
 (11953, u'Gainesville, FL', 78),
 (11953, u'Gainesville, FL', 79),
 (11953, u'Gainesville, FL', 80),
 (11953, u'Gainesville, FL', 81),
 (11953, u'Gainesville, FL', 82),
 (11953, u'Gainesville, FL', 83),
 (11953, u'Gainesville, FL', 84),
 (11953, u'Gainesville, FL', 85),
 (11953, u'Gainesville, FL', 86),
 (11953, u'Gainesville, FL', 87),
 (11953, u'Gainesville, FL', 88),
 (11953, u'Gainesville, FL', 89),
 (11953, u'Gainesville, FL', 90),
 (11953, u'Gainesville, FL', 91),
 (11953, u'Gainesville, FL', 92),
 (11953, u'Gainesville, FL', 93),
 (11953, u'Gainesville, FL', 94),
 (11953, u'Gainesville, FL', 95),
 (11953, u'Gainesville, FL', 96),
 (11953, u'Gainesville, FL', 97),
 (11953, u'Gainesville, FL', 98),
 (11953, u'Gainesville, FL', 99),
 (11953, u'Gainesville, FL', 100)]

从"Dillingham, AK"机场到达 "Gainesville, FL"机场的最少转机次数是（   3  ）次。

2.5 查询是否存在两个机场，无论经多少次转机都无法达到？使用With Recursive实现。（3分）

In [11]:
%%sql
with recursive t(sid,eid)
as (select distinct a.start_node_id, a.end_node_id
    from airport_link as a
    union 
    select t.sid, a.end_node_id
     from t as t, airport_link as a
     where  t.eid = a.start_node_id
     )

select a1.airport_id, a2.airport_id
from airport_list as a1, airport_list as a2
where a1.airport_id != a2.airport_id
except (select * from t)

 * postgresql://postgres:***@localhost:5432/lab6
0 rows affected.

[]

回答是否存在：（   否      ）

2.6 使用pgRouting的[pgr_dijkstra](http://docs.pgrouting.org/latest/en/pgr_dijkstra.html)函数，查询从"Dillingham, AK"机场到达 "Gainesville, FL"机场的最少花费路径，返回seq, node, edge, cost。（2分）

In [16]:
%%time
%%sql 
SELECT seq,node,edge,cost FROM pgr_dijkstra(
    'SELECT link_id as id,  start_node_id as source, end_node_id as target, cost, -1 as reverse_cost FROM  airport_link',
    (select airport_id from airport_list where airport_name='Dillingham, AK'),
	(select airport_id from airport_list where airport_name='Gainesville, FL'),
	false
)

 * postgresql://postgres:***@localhost:5432/lab6
5 rows affected.
Wall time: 10 ms

[(1, 11336L, 742L, 329.0),
 (2, 10299L, 834L, 2519.0),
 (3, 13487L, 1893L, 907.0),
 (4, 10397L, 19L, 300.0),
 (5, 11953L, -1L, 0.0)]

2.7 pgRouting同时提供了[pgr_aStar](http://docs.pgrouting.org/latest/en/pgr_aStar.html)函数，对比Dijkstra算法与Astar算法，并说明在2.6题中为何不能使用pgr_aStar函数？Jupyter Notebook可以使用%%time给出cell的代码运行一次所花费的时间。（2分）

In [18]:
%%time
%%sql
SELECT seq,node,edge,cost FROM pgr_aStar(
    'SELECT link_id as id,  start_node_id as source, end_node_id as target, cost, -1 as reverse_cost ,0 as x1,0 as y1,0 as x2
	,0 as y2 FROM  airport_link',
    (select airport_id from airport_list where airport_name='Dillingham, AK'),
	(select airport_id from airport_list where airport_name='Gainesville, FL'),
	false
)

 * postgresql://postgres:***@localhost:5432/lab6
5 rows affected.
Wall time: 14 ms

[(1, 11336L, 742L, 329.0),
 (2, 10299L, 834L, 2519.0),
 (3, 13487L, 1893L, 907.0),
 (4, 10397L, 19L, 300.0),
 (5, 11953L, -1L, 0.0)]

通过对比发现pgr_aStar函数运行时间更长，此函数还需要顶点标识符的（x，y），而且题目中并没有坐标标识符；

### 3. 深圳地铁网络构建与查询（9分）

地铁是典型的空间网络，深圳目前有8条运行的地铁线路，分别为：

1号线(罗宝线)
罗湖-国贸-老街-大剧院-科学馆-华强路-岗厦-会展中心-购物公园-香蜜湖-车公庙-竹子林-侨城东-华侨城-世界之窗-白石洲-高新园-深大-桃园-大新-鲤鱼门-前海湾-新安-宝安中心-宝体-坪洲-西乡-固戍-后瑞-机场东

2号线(蛇口线)
赤湾-蛇口港-海上世界-水湾-东角头-湾厦-海月-登良-后海-科苑-红树湾-世界之窗-侨城北-深康-安托山-侨香-香蜜-香梅北-景田-莲花西-福田-市民中心-岗厦北-华强北-燕南-大剧院-湖贝-黄贝岭-新秀

3号线(龙岗线)
益田－石厦－购物公园－福田－少年宫－莲花村－华新－通新岭－红岭－老街－晒布－翠竹－田贝－水贝－草埔－布吉－木棉湾－大芬－丹竹头－六约－塘坑－横岗－永湖－荷坳－大运－爱联－吉祥－龙城广场－南联－双龙

4号线(龙华线)
福田口岸－福民－会展中心－市民中心－少年宫－莲花北－上梅林－民乐－白石龙－深圳北站－红山－上塘－龙胜－龙华－清湖

5号线(环中线)
黄贝岭－怡景－太安－布心－白鸽笼－布吉－长龙－下水径－上水径－杨美－坂田－五和－民治－深圳北站－长岭坡－塘朗－大学城－西丽－留仙洞－兴东－洪浪北－灵芝－翻身－宝安中心－宝华－临海－前海湾

7号线(西丽线)
西丽湖-西丽-茶光-珠光-龙井-桃源村-深云-安托山-农林-车公庙-上沙-沙尾-石厦-皇岗村-福民-皇岗口岸-赤尾-华强南-华强北-华新-黄木岗-八卦岭-红岭北-笋岗-洪湖-田贝-太安

9号线(梅林线)
红树湾南-深湾-深圳湾公园-下沙-车公庙-香梅-景田-梅景-下梅林-梅村-上梅林-孖岭-银湖-泥岗-红岭北-园岭-红岭-红岭南-鹿丹村-人民南-向西村-文锦

11号线(机场快线)
福田-车公庙-红树湾南-后海-南山-前海湾-宝安-碧海湾-机场-机场北-福永-桥头-塘尾-马安山-沙井- 后亭-松岗-碧头


百度地图实现了深圳地铁网络站点间的查询，[深圳轨道交通查询](http://map.baidu.com/?subwayShareId=shenzhen,340)。

创建Line(id, lineName, name，geom(LineString, 4326))，Station(id, name, geom(Point, 4326))，Link(id serial, fromStation, toStation, lineID)关系，根据提供的数据确定属性的数据类型，指定关系的主键和外键，并将lines.txt，stations.txt和links.txt导入相应关系中。

In [22]:
%%sql
SET client_encoding = 'GBK';
Drop Table if exists LINK cascade;
Drop Table if exists STATION cascade;
Drop Table if exists LINE cascade;

create table LINE
(
    id INT PRIMARY KEY,
    lineName VARCHAR(50),
    name VARCHAR(50),
    geom geometry(LineString, 4326)
);

create table STATION
(
     id INT PRIMARY KEY,
     name VARCHAR(50),
     geom geometry(Point, 4326)
);

create table LINK
(
    id serial PRIMARY KEY,
    fromStation INT,
    toStation INT,
    lineID INT,
    foreign key (fromStation) references STATION(id),
    foreign key (toStation) references STATION(id),
    foreign key (lineID) references LINE(id)
);

copy line from  'D://desktop//geodatabase//lab//lab6//data//line.txt' delimiter '#';
copy station from  'D://desktop//geodatabase//lab//lab6//data//station.txt' delimiter '#';
copy link from  'D://desktop//geodatabase//lab//lab6//data//link.txt' delimiter '#';

SET client_encoding = 'utf-8';

 * postgresql://postgres:***@localhost:5432/lab6
Done.
Done.
Done.
Done.
Done.
Done.
Done.
8 rows affected.
166 rows affected.
380 rows affected.
Done.

[]

实现以下地铁空间网络的分析与查询，注意不能修改上述关系，如增加属性，不能使用pgRouting函数实现。

3.1 给定地铁线路名称，如“西丽线”，查询该线上的站点数目。(Find the number of stops on the Yellow West (YW) route)

In [13]:
%%sql 
select count(distinct fromstation)
from link join line on link.lineid = line.id
where line.name = '西丽线'

 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.

[(27L,)]

3.2 给定地铁站名称，如“世界之窗”，查询该地铁站所能到达的所有地铁站(可换乘, **路径长度不会超过30**)，使用With Recursive实现。(List all stops which can be reached from Downtown Berkeley (2))（2分）

In [22]:
%%sql 
with recursive x(tos,depth)
as(
    select tostation,0 from link where fromstation=(select id from station
 where name ='世界之窗')
  union select tostation ,depth+1
        from x,link
        where fromstation=x.tos and depth<30 ) 

select distinct tos,name from x,station
where id=tos

 * postgresql://postgres:***@localhost:5432/lab6
166 rows affected.

[(148, u'\u7ea2\u5cad\u5357'),
 (133, u'\u7ea2\u5cad\u5317'),
 (161, u'\u9a6c\u5b89\u5c71'),
 (146, u'\u6ce5\u5c97'),
 (23, u'\u4e1c\u89d2\u5934'),
 (81, u'\u4e0a\u6c34\u5f84'),
 (86, u'\u6df1\u5eb7'),
 (97, u'\u6843\u56ed'),
 (94, u'\u592a\u5b89'),
 (144, u'\u5b56\u5cad'),
 (32, u'\u56fa\u620d'),
 (46, u'\u534e\u5f3a\u8def'),
 (59, u'\u83b2\u82b1\u6751'),
 (12, u'\u8349\u57d4'),
 (79, u'\u6652\u5e03'),
 (48, u'\u534e\u65b0'),
 (134, u'\u7b0b\u5c97'),
 (154, u'\u5b9d\u5b89'),
 (84, u'\u86c7\u53e3\u6e2f'),
 (114, u'\u76ca\u7530'),
 (82, u'\u4e0a\u5858'),
 (54, u'\u79d1\u5b66\u9986'),
 (53, u'\u666f\u7530'),
 (42, u'\u540e\u6d77'),
 (25, u'\u798f\u6c11'),
 (136, u'\u7ea2\u6811\u6e7e\u5357'),
 (131, u'\u9ec4\u6728\u5c97'),
 (57, u'\u9ca4\u9c7c\u95e8'),
 (110, u'\u5174\u4e1c'),
 (5, u'\u767d\u77f3\u6d32'),
 (20, u'\u5927\u8fd0'),
 (151, u'\u5411\u897f\u6751'),
 (157, u'\u673a\u573a\u5317'),
 (121, u'\u9f99\u4e95'),
 (17, u'\u5927\u5267\u9662'),
 (18, u'\u5927\u65b0'),
 (135, u'\u6d2a\u6e56'),
 (93, u'\u6c34\u6e7e'),
 (96, u'\u5858\u6717'),
 (44, u'\u6e56\u8d1d'),
 (123, u'\u6df1\u4e91'),
 (71, u'\u6728\u68c9\u6e7e'),
 (65, u'\u9f99\u57ce\u5e7f\u573a'),
 (85, u'\u6df1\u5927'),
 (72, u'\u5357\u8054'),
 (159, u'\u6865\u5934'),
 (117, u'\u957f\u9f99'),
 (51, u'\u673a\u573a\u4e1c'),
 (129, u'\u8d64\u5c3e'),
 (142, u'\u4e0b\u6885\u6797'),
 (102, u'\u897f\u4e3d'),
 (138, u'\u6df1\u5733\u6e7e\u516c\u56ed'),
 (60, u'\u83b2\u82b1\u897f'),
 (58, u'\u83b2\u82b1\u5317'),
 (29, u'\u5c97\u53a6\u5317'),
 (22, u'\u767b\u826f'),
 (66, u'\u9f99\u534e'),
 (132, u'\u516b\u5366\u5cad'),
 (112, u'\u6768\u7f8e'),
 (6, u'\u5742\u7530'),
 (34, u'\u6d77\u4e0a\u4e16\u754c'),
 (70, u'\u6c11\u6cbb'),
 (63, u'\u7559\u4ed9\u6d1e'),
 (125, u'\u4e0a\u6c99'),
 (26, u'\u798f\u7530'),
 (95, u'\u5858\u5751'),
 (158, u'\u798f\u6c38'),
 (99, u'\u901a\u65b0\u5cad'),
 (9, u'\u5b9d\u4f53'),
 (137, u'\u6df1\u6e7e'),
 (3, u'\u767d\u9e3d\u7b3c'),
 (162, u'\u6c99\u4e95'),
 (37, u'\u6a2a\u5c97'),
 (122, u'\u6843\u6e90\u6751'),
 (92, u'\u6c34\u8d1d'),
 (150, u'\u4eba\u6c11\u5357'),
 (61, u'\u4e34\u6d77'),
 (143, u'\u6885\u6751'),
 (30, u'\u9ad8\u65b0\u56ed'),
 (74, u'\u524d\u6d77\u6e7e'),
 (73, u'\u576a\u6d32'),
 (130, u'\u534e\u5f3a\u5357'),
 (7, u'\u5b9d\u5b89\u4e2d\u5fc3'),
 (35, u'\u6d77\u6708'),
 (140, u'\u9999\u6885'),
 (33, u'\u56fd\u8d38'),
 (124, u'\u519c\u6797'),
 (105, u'\u9999\u6885\u5317'),
 (108, u'\u65b0\u5b89'),
 (116, u'\u957f\u5cad\u5761'),
 (1, u'\u7231\u8054'),
 (10, u'\u5e03\u5409'),
 (104, u'\u4e0b\u6c34\u5f84'),
 (111, u'\u71d5\u5357'),
 (36, u'\u8377\u5773'),
 (152, u'\u6587\u9526'),
 (128, u'\u7687\u5c97\u53e3\u5cb8'),
 (83, u'\u5c11\u5e74\u5bab'),
 (78, u'\u6e05\u6e56'),
 (109, u'\u65b0\u79c0'),
 (127, u'\u7687\u5c97\u6751'),
 (166, u'\u8336\u5149'),
 (139, u'\u4e0b\u6c99'),
 (24, u'\u7ffb\u8eab'),
 (91, u'\u53cc\u9f99'),
 (160, u'\u5858\u5c3e'),
 (119, u'\u897f\u4e3d\u6e56'),
 (4, u'\u767d\u77f3\u9f99'),
 (64, u'\u516d\u7ea6'),
 (19, u'\u5927\u5b66\u57ce'),
 (101, u'\u4e94\u548c'),
 (88, u'\u77f3\u53a6'),
 (163, u'\u540e\u4ead'),
 (118, u'\u7af9\u5b50\u6797'),
 (11, u'\u5e03\u5fc3'),
 (68, u'\u7f57\u6e56'),
 (62, u'\u7075\u829d'),
 (80, u'\u4e0a\u6885\u6797'),
 (103, u'\u897f\u4e61'),
 (67, u'\u9f99\u80dc'),
 (87, u'\u6df1\u5733\u5317\u7ad9'),
 (13, u'\u8f66\u516c\u5e99'),
 (50, u'\u4f1a\u5c55\u4e2d\u5fc3'),
 (153, u'\u5357\u5c71'),
 (21, u'\u4e39\u7af9\u5934'),
 (75, u'\u4fa8\u57ce\u5317'),
 (8, u'\u5b9d\u534e'),
 (27, u'\u798f\u7530\u53e3\u5cb8'),
 (41, u'\u6d2a\u6d6a\u5317'),
 (156, u'\u673a\u573a'),
 (164, u'\u677e\u5c97'),
 (40, u'\u7ea2\u6811\u6e7e'),
 (100, u'\u6e7e\u53a6'),
 (39, u'\u7ea2\u5c71'),
 (49, u'\u9ec4\u8d1d\u5cad'),
 (14, u'\u8d64\u6e7e'),
 (56, u'\u8001\u8857'),
 (38, u'\u7ea2\u5cad'),
 (45, u'\u534e\u5f3a\u5317'),
 (147, u'\u56ed\u5cad'),
 (15, u'\u7fe0\u7af9'),
 (90, u'\u5e02\u6c11\u4e2d\u5fc3'),
 (115, u'\u6c38\u6e56'),
 (98, u'\u7530\u8d1d'),
 (145, u'\u94f6\u6e56'),
 (120, u'\u73e0\u5149'),
 (165, u'\u78a7\u5934'),
 (126, u'\u6c99\u5c3e'),
 (55, u'\u79d1\u82d1'),
 (141, u'\u6885\u666f'),
 (107, u'\u9999\u871c\u6e56'),
 (47, u'\u534e\u4fa8\u57ce'),
 (31, u'\u8d2d\u7269\u516c\u56ed'),
 (52, u'\u5409\u7965'),
 (16, u'\u5927\u82ac'),
 (76, u'\u4fa8\u57ce\u4e1c'),
 (89, u'\u4e16\u754c\u4e4b\u7a97'),
 (2, u'\u5b89\u6258\u5c71'),
 (77, u'\u4fa8\u9999'),
 (155, u'\u78a7\u6d77\u6e7e'),
 (69, u'\u6c11\u4e50'),
 (43, u'\u540e\u745e'),
 (28, u'\u5c97\u53a6'),
 (149, u'\u9e7f\u4e39\u6751'),
 (106, u'\u9999\u871c'),
 (113, u'\u6021\u666f')]

3.3 给定两个地铁站名称，如“机场东”和“少年宫”，查询连接给定地铁站的路径，该路径经过的站点数目最少(假设地铁在任意两站之间的行驶时间相等)，即时间最短的路径(较快捷, **路径长度不会超过30**)，具体可查看[深圳轨道交通查询](http://map.baidu.com/?subwayShareId=shenzhen,340)上的路径查询效果，使用With Recursive实现。(List the routes numbers that connect Downtown Berkeley (2) & Daly City (5))（3分）

In [10]:
#查询经过站点数目最少的地铁路径。返回结果为三元组(gid站点id, name站点名称, geom站点位置),即路径上经过的所有站点
#若query1内容包含汉字，请用decode方法按照utf-8进行解码
query1 = """
WITH recursive X(tos, depth, path, circle) as (
       select fromstation, 0, array[fromstation], false from link where fromstation=
	                                                                       (select id from station where name='机场东')
     UNION
       select tostation, depth + 1, path || tostation, tostation = any(path) 
       from link, X 
       where tos =fromstation  and not circle and depth<30)

select name,id as gid,geom from station, (select  * from X
where tos=(select id from station where name = '少年宫') 
limit 1)aa
where id=any(path)
order by id
""".decode('utf-8')

result1 = %sql $query1

#根据results的路径查询结果，返回经过的地铁路径。返回结果为三元组(gid地铁线号, name其由linename和name拼接而成, geom地铁路线的几何信息)
query2 = """
WITH recursive X(tos, depth, path, circle) as (
       select fromstation, 0, array[fromstation], false from link where fromstation=
	                                                                       (select id from station where name='机场东')
     UNION
       select tostation, depth + 1, path || tostation, tostation = any(path) 
       from link, X 
       where tos =fromstation  and not circle and depth<30)
select gid,linename||name as name,geom from line,(
select distinct lineid as gid  from link, (select  * from X  
where tos=(select id from station where name = '少年宫') 
limit 1)aa
where fromstation=any(path) and tostation=any(path))foo
											  where foo.gid=id
					
""".decode('utf-8')


result2 = %sql $query2

display([result1, result2], "map1", 12, showToolTipLayer = 1, baseMapType = 0)

 * postgresql://postgres:***@localhost:5432/lab6
15 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
3 rows affected.

3.4 给定两个地铁站名称，如“机场东”和“少年宫”，查询连接给定地铁站的路径，该路径换乘次数最少(**路径长度不会超过30**)，具体可查看[深圳轨道交通查询](http://map.baidu.com/?subwayShareId=shenzhen,340)上的路径查询效果，使用With Recursive实现。(List the routes numbers that connect Downtown Berkeley (2) & Daly City (5))（4分）

In [7]:
#查询换乘次数最少的地铁路径。返回结果为三元组(gid站点id, name站点名称, geom站点位置),即路径上经过的所有站点
#若query1内容包含汉字，请用decode方法按照utf-8进行解码
query1 = """
WITH recursive X(tos, depth, path, circle,hc,dd) as (
       select fromstation, 0, array[fromstation], false,array[ 0],false from link where fromstation=
	                                                                       (select id from station where name='机场东')
     UNION
       select tostation, depth + 1, path || tostation, tostation = any(path),hc||lineid ,lineid=any(hc)
       from link, X 
       where fromstation = tos and not circle and depth<30)
	   
	   
 select name,id as gid,geom from station, (select tos ,depth,path,hc,icount(uniq(sort(hc)))-1 as transfer  from x
	   where tos=(select id from station where name = '少年宫') and circle=false
												  order by transfer,depth
												  limit 1)aa
where id=any(path)

""".decode('utf-8')

result1 = %sql $query1

#根据results的路径查询结果，返回经过的地铁路径。返回结果为三元组(gid地铁线号, name其由linename和name拼接而成, geom地铁路线的几何信息)
query2 = """
WITH recursive X(tos, depth, path, circle,hc,dd) as (
       select fromstation, 0, array[fromstation], false,array[ 0],false from link where fromstation=
	                                                                       (select id from station where name='机场东')
     UNION
       select tostation, depth + 1, path || tostation, tostation = any(path),hc||lineid ,lineid=any(hc)
       from link, X 
       where fromstation = tos and not circle and depth<30)
select  id as gid,linename||name as name,geom  from line,	   
(select tos ,depth,path,hc,icount(uniq(sort(hc)))-1 as transfer  from x
	   where tos=(select id from station where name = '少年宫') and circle=false
												  order by transfer,depth
												  limit 1)foo
									   where id=any(hc)

""".decode('utf-8')
result2 = %sql $query2

display([result1, result2], "map2", 12, showToolTipLayer = 1, baseMapType = 0)

 * postgresql://postgres:***@localhost:5432/lab6
24 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
2 rows affected.

3.5 (练习题) 给定地铁线路名称，如“环中线”，查询该线上的起点或终点的地铁站。(Find the last stop on the Blue West (BW) route)

In [ ]:
%%sql

3.6 (附加题) [深圳轨道交通查询](http://map.baidu.com/?subwayShareId=shenzhen,340)提供了“较快捷”和“少换乘”两种查询模式，是否存在两个地铁站点的“较快捷”和“少换乘”路径不同？如果有请至少举例一对这样的站点，并修改3.3和3.4的站点名称，显示不同路径，如果没有，请说明理由。（1分）

### 4. 杭州道路网路构建与最短路径查询（24分）

Geocoding类库[geopy](https://github.com/geopy/geopy)利用the OpenStreetMap Nominatim, ESRI ArcGIS, Google Geocoding API (V3), Baidu Maps, Bing Maps API, Yahoo! PlaceFinder, Yandex, IGN France, GeoNames, NaviData, OpenMapQuest, What3Words, OpenCage, SmartyStreets, geocoder.us, and GeocodeFarm geocoder services，通过地址可以获得经纬度，或者通过经纬度获得地址，可以用于解决Lecture 11 Location Based Services中的Location: Where am I?问题。

基于OpenStreetMap上的杭州道路数据，包括poi(point of interest 点数据)和road(道路数据)，构建杭州道路网络，实现杭州道路上的最短路径查询。所建立的杭州道路网络为无向网络，在导航的过程中无需考虑道路单行道及走向问题。几何展示使用display函数，其查询结果至少包含gid，name和geom属性。

#### 4.0 Geocoding

Python函数address2location，输入地址字符串，返回经纬度。由于实习使用OpenStreetMap的道路数据，geocoding使用的是OpenStreetMap的Nominatim类。

In [3]:
from geopy.geocoders import Nominatim

def address2location(address):
    geolocator = Nominatim(timeout=10000)
    location   = geolocator.geocode(address)
    return (location.latitude, location.longitude)

In [4]:
addresses = ["浙江大学紫金港校区", "浙江大学玉泉校区", "浙江大学西溪校区", "浙江大学华家池校区"]

for address in addresses:
    point = address2location(address)
    print address + "经纬度是(" + str(point[0]) + ", " + str(point[1]) + ")"

i:\python27\python27newfordatebase\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  after removing the cwd from sys.path.

浙江大学紫金港校区经纬度是(30.3043168, 120.076331798)
浙江大学玉泉校区经纬度是(30.2665272, 120.118043182)
浙江大学西溪校区经纬度是(30.2768278, 120.13663991)
浙江大学华家池校区经纬度是(30.270785, 120.191091474)

#### 4.1 数据类型转换（3分）

道路的几何类型可能为ST_MultiLineString，如美国高速公路，但pgRouting是基于ST_LineString几何类型（思考为何不能使用ST_MultiLineString类型）。使用with recursive语句，将road_multilinestring关系的MultiLineString转换为LineString，保存在road_linestring关系中，**不能硬编码MultiLineString中的LineString的数目**。其中，name字段命名规则为road_multilinestring的name字段与该LineString的序号的拼接，中间用'.'分开。例如，"A"公路的MultiLineString包含4条LineString，则依次命名为"A.1", "A.2", "A.3"和"A.4"。

In [5]:
%%sql 
drop table if exists road_multilinestring;
CREATE TABLE road_multilinestring (
    gid serial primary key, 
    name character varying(20),
    geom geometry(MultiLineString, 4326)
);

insert into road_multilinestring(name, geom) values ('A', ST_GeomFromText('MultiLineString((1 1, 2 2, 3 3),(4 5, 6 7, 8 9),(4 5, 6 7, 8 9),(6 5, 4 3, 2 1))', 4326));
insert into road_multilinestring(name, geom) values ('B', ST_GeomFromText('MultiLineString((1 1, 2 2, 3 3),(4 5, 6 7, 8 9))', 4326));

drop table if exists road_linestring;
CREATE TABLE road_linestring (
    gid serial primary key, 
    name character varying(20),
    geom geometry(LineString, 4326)
);
with recursive X(gid,name,depth) as
(
	select gid,name||'.1',1
	from road_multilinestring
union 
	select X.gid,x.name||'.'||depth+1,depth+1
	from road_multilinestring as h,X
	where h.gid=X.gid and depth<ST_NumGeometries(h.geom)
)
insert into  road_linestring(name,geom)  
select left(x.name,1)||'.'||right(x.name,1), ST_GeometryN(geom, depth)
from X join road_multilinestring on X.gid=road_multilinestring.gid;

 * postgresql://postgres:***@localhost:5432/lab6
Done.
Done.
1 rows affected.
1 rows affected.
Done.
Done.
6 rows affected.

[]

In [6]:
%sql select name, ST_AsText(geom) from road_linestring order by name

 * postgresql://postgres:***@localhost:5432/lab6
6 rows affected.

[(u'A.1', u'LINESTRING(1 1,2 2,3 3)'),
 (u'A.2', u'LINESTRING(4 5,6 7,8 9)'),
 (u'A.3', u'LINESTRING(4 5,6 7,8 9)'),
 (u'A.4', u'LINESTRING(6 5,4 3,2 1)'),
 (u'B.1', u'LINESTRING(1 1,2 2,3 3)'),
 (u'B.2', u'LINESTRING(4 5,6 7,8 9)')]

#### 4.2 杭州道路网络构建（3分）

实现人造道路上的道路网络构建，在pgAdmin 4中执行pgr_createTopology，pgr_analyzeGraph，pgr_nodeNetwork函数，生成道路空间网络模型。利用sql语句将自动生成的边表和顶点表信息分别插入到edges(注意len字段的更新)和nodes中。edges表的name字段命名规则为road的name字段与分割后subid字段的拼接，中间用'.'分开，例如，"A"道路经过分割后的道路名称未"A.1"和"A.2"，相邻的节点需要合并。
<img src = "roads.png">

In [4]:
%%sql
drop table if exists roads;
drop table if exists edges;
drop table if exists nodes;

create table roads (
    id integer NOT NULL,
    name text,
    geom geometry(LineString,4326)
);

insert into roads values (1, 'A', ST_GeomFromText('LineString(0 0, 10 0)', 4326));
insert into roads values (2, 'B', ST_GeomFromText('LineString(0 0, 0 10)', 4326));
insert into roads values (3, 'C', ST_GeomFromText('LineString(0 10, 10 10)', 4326));
insert into roads values (4, 'D', ST_GeomFromText('LineString(10 0, 10 15)', 4326));
insert into roads values (5, 'E', ST_GeomFromText('LineString(0 5, 10 15)', 4326));
insert into roads values (6, 'F', ST_GeomFromText('LineString(5 0, 10 5)', 4326));
insert into roads values (7, 'G', ST_GeomFromText('LineString(0 10, 10 0)', 4326));
insert into roads values (8, 'H', ST_GeomFromText('LineString(5 10, 15 0)', 4326));

create table edges (
       id serial primary key,
       name text,
       source int,
       target int,
       geom geometry(LineString, 4326),
       len float);

create table nodes (
       id serial primary key,
       geom geometry(Point, 4326)
);

 * postgresql://postgres:***@localhost:5432/lab6
Done.
Done.
Done.
Done.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
Done.
Done.

[]

根据道路网络构建实验回答以下问题：
Splitted Edges: 8    Untouched Edges: 0   Total original Edges: 8
Edges generated: 22    Total New segments:22
         
edges的数目为( 22  )，nodes的数目为(  15  )

In [5]:
%sql select id, name, source, target, ST_AsText(geom), len from edges;

 * postgresql://postgres:***@localhost:5432/lab6
22 rows affected.

[(1, u'A.1', 1, 2, u'LINESTRING(0 0,5 0)', 5.0),
 (2, u'A.2', 2, 3, u'LINESTRING(5 0,10 0)', 5.0),
 (3, u'B.1', 1, 4, u'LINESTRING(0 0,0 5)', 5.0),
 (4, u'B.2', 4, 5, u'LINESTRING(0 5,0 10)', 5.0),
 (5, u'C.1', 5, 6, u'LINESTRING(0 10,5 10)', 5.0),
 (6, u'C.2', 6, 7, u'LINESTRING(5 10,10 10)', 5.0),
 (7, u'D.3', 3, 8, u'LINESTRING(10 0,10 5)', 5.0),
 (8, u'D.4', 8, 7, u'LINESTRING(10 5,10 10)', 5.0),
 (9, u'D.6', 7, 9, u'LINESTRING(10 10,10 15)', 5.0),
 (10, u'E.5', 4, 10, u'LINESTRING(0 5,2.5 7.5)', 3.53553390593274),
 (11, u'E.8', 10, 6, u'LINESTRING(2.5 7.5,5 10)', 3.53553390593274),
 (12, u'E.9', 6, 11, u'LINESTRING(5 10,7.5 12.5)', 3.53553390593274),
 (13, u'E.10', 11, 9, u'LINESTRING(7.5 12.5,10 15)', 3.53553390593274),
 (14, u'F.3', 2, 12, u'LINESTRING(5 0,7.5 2.5)', 3.53553390593274),
 (15, u'F.6', 12, 8, u'LINESTRING(7.5 2.5,10 5)', 3.53553390593274),
 (16, u'G.2', 5, 10, u'LINESTRING(0 10,2.5 7.5)', 3.53553390593274),
 (17, u'G.3', 10, 12, u'LINESTRING(2.5 7.5,7.5 2.5)', 7.07106781186548),
 (18, u'G.4', 12, 3, u'LINESTRING(7.5 2.5,10 0)', 3.53553390593274),
 (19, u'H.3', 6, 13, u'LINESTRING(5 10,7.5 7.5)', 3.53553390593274),
 (20, u'H.4', 13, 8, u'LINESTRING(7.5 7.5,10 5)', 3.53553390593274),
 (21, u'H.5', 8, 14, u'LINESTRING(10 5,12.5 2.5)', 3.53553390593274),
 (22, u'H.6', 14, 15, u'LINESTRING(12.5 2.5,15 0)', 3.53553390593274)]

In [6]:
%sql select id, ST_AsText(geom) from nodes;

 * postgresql://postgres:***@localhost:5432/lab6
15 rows affected.

[(1, u'POINT(0 0)'),
 (2, u'POINT(5 0)'),
 (3, u'POINT(10 0)'),
 (4, u'POINT(0 5)'),
 (5, u'POINT(0 10)'),
 (6, u'POINT(5 10)'),
 (7, u'POINT(10 10)'),
 (8, u'POINT(10 5)'),
 (9, u'POINT(10 15)'),
 (10, u'POINT(2.5 7.5)'),
 (11, u'POINT(7.5 12.5)'),
 (12, u'POINT(7.5 2.5)'),
 (13, u'POINT(7.5 7.5)'),
 (14, u'POINT(12.5 2.5)'),
 (15, u'POINT(15 0)')]

由于pgRounting的网络构建的随机性和杭州道路的复杂性，杭州道路网路将直接导入，用于4.3-4.8的道路网络查询。

In [9]:
%%sql
set client_encoding = 'GBK';
drop table if exists poi; 
drop table if exists edges1;
drop table if exists nodes1;

create table poi (
    id integer NOT NULL,
    lon double precision,
    lat double precision,
    name text,
    geom geometry(Point,4326)
);

create table edges1 (
       id serial primary key,
       name text,
       source int,
       target int,
       geom geometry(LineString, 4326),
       len float);

create table nodes1 (
       id serial primary key,
       name text,
       geom geometry(Point, 4326)
);

copy poi   from  'D://desktop//geodatabase//lab//lab6//data//poi.txt'   delimiter '#';
set client_encoding = 'utf-8';
copy edges1 from  'D://desktop//geodatabase//lab//lab6//data//edges.txt' delimiter '#';
copy nodes1 from  'D://desktop//geodatabase//lab//lab6//data//nodes.txt' delimiter '#';

 * postgresql://postgres:***@localhost:5432/lab6
Done.
Done.
Done.
Done.
Done.
Done.
Done.
2200 rows affected.
Done.
10673 rows affected.
6766 rows affected.

[]

#### 4.3 最近的道路网络节点（2分）

在路径导航过程中，假设出发和目的地都先走路到道路网络节点，通过ST_Location2Node函数获得当前位置最近的道路网络节点，再通过道路网络节点之间的最短距离实现Lecture 11 Location Based Services的Routes: How do I get there?问题。

实现ST_Location2Node函数，输入经纬度位置，输出道路网络中，离该位置直线距离最近的道路网络端点。

In [7]:
%%sql
create or replace function ST_Location2Node(la float, lo float) 
    returns integer
as $$
declare num integer;
begin
    select id into num 
    from nodes1
    order by st_distance(geom, ST_SetSRID(ST_MakePoint(lo, la), 4326))
    limit 1;
    
    return num;
end;


$$ language plpgsql;

 * postgresql://postgres:***@localhost:5432/lab6
Done.

[]

In [8]:
addresses = ["浙江大学紫金港校区", "浙江大学玉泉校区", "浙江大学西溪校区", "浙江大学华家池校区"]

for address in addresses:
    point = address2location(address)
    query = "select ST_Location2Node(%s, %s)" % (point[0], point[1])
    result = %sql $query
    print address + "直线距离最近的网络节点是" + str(result[0][0])

i:\python27\python27newfordatebase\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  after removing the cwd from sys.path.

 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
浙江大学紫金港校区直线距离最近的网络节点是422
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
浙江大学玉泉校区直线距离最近的网络节点是789
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
浙江大学西溪校区直线距离最近的网络节点是1044
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
浙江大学华家池校区直线距离最近的网络节点是2057

#### 4.4 导航路径生成（Dijkstra算法）（2分）

根据4.3的查询结果，使用pg_dijkstra算法，查询从紫金港校区到西溪校区的最短驾驶距离对应的路线，查询结果至少包含gid，name和geom属性。

In [120]:
query = """    
select seq as gid, name,geom 
from pgr_dijkstra(
'select id,source,target,len as cost from edges1' ,422,1044,false) as path,edges1
where path.edge=id
""".decode('utf-8')
result = %sql $query

display([result], "map3", 13)

 * postgresql://postgres:***@localhost:5432/lab6
32 rows affected.

#### 4.5 驾驶距离最近的电影院（6分）

Lecture 11 Location Based Services的Directory: What is around me?，例如查询浙江大学西溪校区<b>直线距离最近</b>的电影院，注意本题共有**5处(修改此处)**需要修改。

In [13]:
point = address2location("浙江大学西溪校区")
query = """select id, name, ST_AsText(geom) from poi where name like '%%电影%%' or name like '%%影院%%' or name like '%%影城%%' 
           order by ST_Distance(geom,ST_GeomFromText('Point(%s %s)',4326))""".decode('utf-8') % (point[1], point[0])
print query

i:\python27\python27newfordatebase\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  after removing the cwd from sys.path.

select id, name, ST_AsText(geom) from poi where name like '%电影%' or name like '%影院%' or name like '%影城%'
           order by ST_Distance(geom,ST_GeomFromText('Point(120.13663991,30.2768278)',4326))

In [14]:
point = address2location("浙江大学西溪校区")
query = """select id, name, ST_AsText(geom) from poi where name like '%%电影%%' or name like '%%影院%%' or name like '%%影城%%' 
           order by ST_Distance(geom,ST_GeomFromText('Point(%s %s)',4326))""".decode('utf-8') % (point[1], point[0])
print query
result = %sql $query
print result

i:\python27\python27newfordatebase\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  after removing the cwd from sys.path.

select id, name, ST_AsText(geom) from poi where name like '%电影%' or name like '%影院%' or name like '%影城%'
           order by ST_Distance(geom,ST_GeomFromText('Point(120.13663991 30.2768278)',4326))
 * postgresql://postgres:***@localhost:5432/lab6
5 rows affected.
+------+------------------+-------------------------------+
|  id  |       name       |           st_astext           |
+------+------------------+-------------------------------+
| 2199 |     黄龙影城     |   POINT(120.141376 30.27236)  |
| 2198 |   杭州金象影城   |  POINT(120.123847 30.303253)  |
| 2197 | 杭州传奇奢华影院 |  POINT(120.115372 30.306828)  |
| 2114 |  庆春电影大世界  | POINT(120.1732711 30.2606449) |
| 2200 |    近江电影院    |  POINT(120.198551 30.245813)  |
+------+------------------+-------------------------------+

实际上，希望查询驾驶距离最近的电影院('%电影%' or '%影院%', or '%影城%')，而非直线距离最近。基于当前位置的经纬度，输出驾驶距离最近的电影院，POI的id。忽略走路距离，位置到最近网络节点编号查询使用ST_Location2Node函数。通过查询最短驾驶距离，也实现了Lecture 11 Location Based Services的Routes: How do I get there?问题。

实现思路：依次遍历所有电影院，通过Dijkstra最短路径算法获得路径，计算总的路程，获得驾驶距离最短的电影院编号。

思考是否有更高效的方法，减少最短路径查询次数。

In [15]:
point = address2location("浙江大学西溪校区")
result = %sql select id, ST_X(geom), ST_Y(geom) from poi where name like '%电影%' or name like '%影院%'  or name like '%影城%'
print len(result)

i:\python27\python27newfordatebase\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  after removing the cwd from sys.path.

 * postgresql://postgres:***@localhost:5432/lab6
5 rows affected.
5

In [18]:
point = address2location("浙江大学西溪校区")
result = %sql select id, ST_X(geom), ST_Y(geom) from poi where name like '%电影%' or name like '%影院%'  or name like '%影城%'
print len(result)

cinmaID = -1
minLength = 1e10
for cinma in result:
    query1 = "select ST_Location2Node(%f,%f) as id" %(point[0], point[1])
    closestp1 = %sql $query1
    query2 = "select ST_Location2Node(%f,%f) as id" %(cinma[2], cinma[1])
    closestp2 = %sql $query2
    query = """
       select agg_cost
		from pgr_dijkstra(
		'select id,source,target,len as cost from edges1' ,%d,%d,false)
		order by seq desc
		limit 1
            """ %(closestp1[0]['id'], closestp2[0]['id'])
    length = %sql $query
    if length[0][0] < minLength:
        minLength = length[0][0]
        cinmaID = cinma[0]

print cinmaID, minLength

i:\python27\python27newfordatebase\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  after removing the cwd from sys.path.

 * postgresql://postgres:***@localhost:5432/lab6
5 rows affected.
5
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
2199 0.568831801483

在OpenStreetMap上展示从浙江大学西溪校区到其驾驶距离最近电影院的导航路径

In [36]:
point = address2location("浙江大学西溪校区")
query1 = "select ST_Location2Node(%f,%f) as id" %(point[0], point[1])
closestp1 = %sql $query1
print closestp1[0]['id']

cinma = %sql select ST_X(geom), ST_Y(geom) from poi where id = 2199
query2 = "select ST_Location2Node(%f,%f) as id" %(cinma[0][1], cinma[0][0])
closestp2 = %sql $query2
print closestp2[0]['id']

#查询这两个网络节点之间的最短路径，输出为(gid,name,geom)三元组
query1 = """
        select id as gid ,name,geom from
        (select *
		from pgr_dijkstra(
		'select id,source,target,len as cost from edges1',%d,%d,false)
		)foo,edges1
        where foo.edge=edges1.id

""" %(closestp1[0]['id'], closestp2[0]['id'])
result1 = %sql $query1

#查询这两个网络节点的几何信息，输出为(gid,name,geom)三元组
query2 = """
select id as gid, name,geom
from nodes1
where id = %d or id =%d
"""%(closestp1[0]['id'], closestp2[0]['id'])
result2 = %sql $query2

display([result1, result2], "map4", 13)

i:\python27\python27newfordatebase\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: Using Nominatim with the default "geopy/1.18.1" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  after removing the cwd from sys.path.

 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
1044
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.
3897
 * postgresql://postgres:***@localhost:5432/lab6
6 rows affected.
 * postgresql://postgres:***@localhost:5432/lab6
2 rows affected.

#### 4.6 导航路径推荐 （4分）

当查询从A到B的驾驶路线时，地图服务商（例如高德地图）通常会提供几条路线供用户选择，其中一条是最短驾驶距离对应的路线，其他路线可能会考虑当时的交通状况，例如某条道路当前比较拥堵，行驶缓慢，将提供避开此道路的最短驾驶距离对应的路线。

根据4.3的查询结果，基于Dijkstra算法生成从紫金港校区到玉泉校区的最短驾驶距离对应的路线，查询结果至少包含gid，name和geom属性。

<img src="routes.png" width = 400>

In [39]:
query = """    
select seq as gid, name,geom 
from pgr_dijkstra(
'select id,source,target,len as cost from edges1' ,422,789,false) as path,edges1
where path.edge=edges1.id
"""
result = %sql $query

display([result], "map5", 13)

 * postgresql://postgres:***@localhost:5432/lab6
27 rows affected.

假设以下道路存在拥堵

    "竞舟路.9.1.1.1.1.1.1", 起点为"POINT(120.0987188 30.2888717)", 终点为"POINT(120.1000613 30.2841765)" 
    "西溪路 Xixi Road.22.1.1.1.1.1.1", 起点为"POINT(120.1197977 30.2719367)", 终点为"POINT(120.1240717 30.2703345)"
    
根据4.3的查询结果，基于Dijkstra算法生成此时从紫金港校区到玉泉校区不包含上述道路的最短驾驶距离对应的路线，查询结果至少包含gid，name和geom属性。

In [47]:
query = """ 
select seq as gid, name,geom 
from pgr_dijkstra(
'select id,source,target,len as cost from edges1
where id!=71493 and id!=75381' ,422,789,false) as path,edges1
where path.edge=id
""".decode('utf-8')
result = %sql $query

display([result], "map6", 13)

 * postgresql://postgres:***@localhost:5432/lab6
22 rows affected.

#### 4.7 导航偏离下重新导航（4分）

根据4.3的查询结果，基于Dijkstra算法生成从紫金港校区到西溪校区的最短驾驶距离对应的路线，查询结果至少包含gid，name和geom属性。

In [48]:
query = """
select seq as gid, name,geom 
from pgr_dijkstra(
'select id,source,target,len as cost from edges1' ,422,1044,false) as path,edges1
where path.edge=edges1.id
select id as gid ,name,geom
where name=''
"""
result = %sql $query

display([result], "map7", 13)

 * postgresql://postgres:***@localhost:5432/lab6
32 rows affected.

当系统发现用户偏离了原始的导航路线，根据当前情况，将自动重新计算最短驾驶距离对应的路线。这里涉及到<a href="http://www.csdn.net/article/1970-01-01/2826221" target="_blank">定位和道路匹配</a>模块，即将用户匹配到某条道路上。

假设在实际行驶过程中，某车本应从"文一西路.24.1.1.1.1.1.1"转向"竞舟路.9.1.1.1.1.1.1"，却前行到"文一西路.25.1.1.1.1.1.1"（中间有绿化带，不能随意掉头返回到"竞舟路.9.1.1.1.1.1.1"）。根据车所在的位置和行驶方向，基于Dijkstra算法重新计算最短驾驶距离对应的路线。

    "文一西路.24.1.1.1.1.1.1", 起点为"POINT(120.0940602 30.2887916)", 终点为"POINT(120.0987188 30.2888717)"
    "竞舟路.9.1.1.1.1.1.1", 起点为"POINT(120.0987188 30.2888717)", 终点为"POINT(120.1000613 30.2841765)"   
    "文一西路.25.1.1.1.1.1.1", 起点为"POINT(120.0987188 30.2888717)", 终点为"POINT(120.102833 30.2890362)"

In [117]:
%%sql
--查询离
--文一西路.25.1.1.1.1.1.1 终点最近的道路结点
select id from nodes1
order by st_distance(geom,(

select geom from ST_Dumppoints((select geom from edges1 where name ='文一西路.25.1.1.1.1.1.1'))
order by path desc limit 1))
	limit 1

 * postgresql://postgres:***@localhost:5432/lab6
1 rows affected.

[(4616,)]

In [118]:
query = """
--4616为离文一西路.25.1.1.1.1.1.1 终点最近的道路结点，75074是该路的ID
select seq as gid, name,geom 
from pgr_dijkstra(
'select id,source,target,len as cost from edges1',
4616,1044,false) as path,edges1
where path.edge=id
union 
select id as gid ,name,geom
from edges1
where id=75074
"""
result = %sql $query

display([result], "map8", 15)

 * postgresql://postgres:***@localhost:5432/lab6
21 rows affected.

#### 4.8 (附加题) 红绿灯最少的路径（4分）

假设每个节点都有红绿灯，根据4.3的查询结果，查询从紫金港校区到西溪校区的经过红绿灯最少的路线，查询结果至少包含gid，name和geom属性。该路线忽略道路长度，仅考虑路线经过的红绿灯数目，不能修改杭州道路网络。

In [ ]:
query = """

"""
result = %sql $query

display([result], "map9", 13)

进一步要求经过红绿灯最少的路线长度不能超过最短路径长度的1.5倍，查询结果至少包含gid，name和geom属性，不能修改杭州道路网络。

In [ ]:
query = """

"""
result = %sql $query

display([result], "map10", 13)

### 实习感想

收获:-)，疑惑:-|，吐槽:-(，...，你的反馈很重要